/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface ArbadCreditLineInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "FAMILY_BASE_LIMIT"
      | "MAX_CREDIT_LIMIT"
      | "MAX_RATING"
      | "NEUTRAL_RATING"
      | "ORG_BASE_LIMIT"
      | "arbadCompletion"
      | "borrowFamily"
      | "borrowOrg"
      | "familyCreditLines"
      | "familyLoans"
      | "getFamilyCreditLine"
      | "getOrgCreditLine"
      | "hasFamilyCreditLine"
      | "hasOrgCreditLine"
      | "interestRateBps"
      | "nextLoanId"
      | "openFamilyCreditLine"
      | "openOrgCreditLine"
      | "orgCreditLines"
      | "orgLoans"
      | "owner"
      | "repayFamily"
      | "repayOrg"
      | "setInterestRate"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CreditLineOpened"
      | "InterestRateUpdated"
      | "LoanRepaid"
      | "LoanTaken"
      | "OwnerChanged"
      | "RatingUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "FAMILY_BASE_LIMIT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_CREDIT_LIMIT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_RATING",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "NEUTRAL_RATING",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ORG_BASE_LIMIT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "arbadCompletion",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "borrowFamily",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "borrowOrg",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "familyCreditLines",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "familyLoans",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getFamilyCreditLine",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getOrgCreditLine",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasFamilyCreditLine",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasOrgCreditLine",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "interestRateBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nextLoanId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "openFamilyCreditLine",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "openOrgCreditLine",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "orgCreditLines",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "orgLoans",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "repayFamily",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "repayOrg",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setInterestRate",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "FAMILY_BASE_LIMIT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_CREDIT_LIMIT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "MAX_RATING", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "NEUTRAL_RATING",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ORG_BASE_LIMIT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "arbadCompletion",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "borrowFamily",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "borrowOrg", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "familyCreditLines",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "familyLoans",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFamilyCreditLine",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOrgCreditLine",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasFamilyCreditLine",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasOrgCreditLine",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "interestRateBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "nextLoanId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "openFamilyCreditLine",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "openOrgCreditLine",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "orgCreditLines",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "orgLoans", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "repayFamily",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "repayOrg", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setInterestRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace CreditLineOpenedEvent {
  export type InputTuple = [
    arbadId: BigNumberish,
    creditType: BigNumberish,
    creditLimit: BigNumberish
  ];
  export type OutputTuple = [
    arbadId: bigint,
    creditType: bigint,
    creditLimit: bigint
  ];
  export interface OutputObject {
    arbadId: bigint;
    creditType: bigint;
    creditLimit: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InterestRateUpdatedEvent {
  export type InputTuple = [oldRateBps: BigNumberish, newRateBps: BigNumberish];
  export type OutputTuple = [oldRateBps: bigint, newRateBps: bigint];
  export interface OutputObject {
    oldRateBps: bigint;
    newRateBps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LoanRepaidEvent {
  export type InputTuple = [
    loanId: BigNumberish,
    arbadId: BigNumberish,
    creditType: BigNumberish,
    onTime: boolean
  ];
  export type OutputTuple = [
    loanId: bigint,
    arbadId: bigint,
    creditType: bigint,
    onTime: boolean
  ];
  export interface OutputObject {
    loanId: bigint;
    arbadId: bigint;
    creditType: bigint;
    onTime: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LoanTakenEvent {
  export type InputTuple = [
    loanId: BigNumberish,
    arbadId: BigNumberish,
    creditType: BigNumberish,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    loanId: bigint,
    arbadId: bigint,
    creditType: bigint,
    amount: bigint
  ];
  export interface OutputObject {
    loanId: bigint;
    arbadId: bigint;
    creditType: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnerChangedEvent {
  export type InputTuple = [oldOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [oldOwner: string, newOwner: string];
  export interface OutputObject {
    oldOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RatingUpdatedEvent {
  export type InputTuple = [
    arbadId: BigNumberish,
    creditType: BigNumberish,
    newRating: BigNumberish
  ];
  export type OutputTuple = [
    arbadId: bigint,
    creditType: bigint,
    newRating: bigint
  ];
  export interface OutputObject {
    arbadId: bigint;
    creditType: bigint;
    newRating: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ArbadCreditLine extends BaseContract {
  connect(runner?: ContractRunner | null): ArbadCreditLine;
  waitForDeployment(): Promise<this>;

  interface: ArbadCreditLineInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  FAMILY_BASE_LIMIT: TypedContractMethod<[], [bigint], "view">;

  MAX_CREDIT_LIMIT: TypedContractMethod<[], [bigint], "view">;

  MAX_RATING: TypedContractMethod<[], [bigint], "view">;

  NEUTRAL_RATING: TypedContractMethod<[], [bigint], "view">;

  ORG_BASE_LIMIT: TypedContractMethod<[], [bigint], "view">;

  arbadCompletion: TypedContractMethod<[], [string], "view">;

  borrowFamily: TypedContractMethod<
    [
      familyArbadId: BigNumberish,
      amount: BigNumberish,
      durationDays: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  borrowOrg: TypedContractMethod<
    [
      orgArbadId: BigNumberish,
      amount: BigNumberish,
      durationDays: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  familyCreditLines: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint
      ] & {
        arbadId: bigint;
        creditType: bigint;
        creditRating: bigint;
        creditLimit: bigint;
        borrowed: bigint;
        totalBorrowed: bigint;
        totalRepaid: bigint;
        defaultCount: bigint;
        onTimeCount: bigint;
        isActive: boolean;
        openedAt: bigint;
      }
    ],
    "view"
  >;

  familyLoans: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean
      ] & {
        loanId: bigint;
        arbadId: bigint;
        creditType: bigint;
        principal: bigint;
        interest: bigint;
        dueDate: bigint;
        borrowedAt: bigint;
        repaidAt: bigint;
        active: boolean;
        defaulted: boolean;
      }
    ],
    "view"
  >;

  getFamilyCreditLine: TypedContractMethod<
    [arbadId: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, boolean] & {
        rating: bigint;
        limit: bigint;
        borrowed: bigint;
        available: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  getOrgCreditLine: TypedContractMethod<
    [arbadId: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, boolean] & {
        rating: bigint;
        limit: bigint;
        borrowed: bigint;
        available: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  hasFamilyCreditLine: TypedContractMethod<
    [arg0: BigNumberish],
    [boolean],
    "view"
  >;

  hasOrgCreditLine: TypedContractMethod<
    [arg0: BigNumberish],
    [boolean],
    "view"
  >;

  interestRateBps: TypedContractMethod<[], [bigint], "view">;

  nextLoanId: TypedContractMethod<[], [bigint], "view">;

  openFamilyCreditLine: TypedContractMethod<
    [familyArbadId: BigNumberish],
    [void],
    "nonpayable"
  >;

  openOrgCreditLine: TypedContractMethod<
    [orgArbadId: BigNumberish],
    [void],
    "nonpayable"
  >;

  orgCreditLines: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint
      ] & {
        arbadId: bigint;
        creditType: bigint;
        creditRating: bigint;
        creditLimit: bigint;
        borrowed: bigint;
        totalBorrowed: bigint;
        totalRepaid: bigint;
        defaultCount: bigint;
        onTimeCount: bigint;
        isActive: boolean;
        openedAt: bigint;
      }
    ],
    "view"
  >;

  orgLoans: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean
      ] & {
        loanId: bigint;
        arbadId: bigint;
        creditType: bigint;
        principal: bigint;
        interest: bigint;
        dueDate: bigint;
        borrowedAt: bigint;
        repaidAt: bigint;
        active: boolean;
        defaulted: boolean;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  repayFamily: TypedContractMethod<
    [familyArbadId: BigNumberish, loanIdx: BigNumberish],
    [void],
    "nonpayable"
  >;

  repayOrg: TypedContractMethod<
    [orgArbadId: BigNumberish, loanIdx: BigNumberish],
    [void],
    "nonpayable"
  >;

  setInterestRate: TypedContractMethod<
    [rateBps: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "FAMILY_BASE_LIMIT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_CREDIT_LIMIT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_RATING"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "NEUTRAL_RATING"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "ORG_BASE_LIMIT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "arbadCompletion"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "borrowFamily"
  ): TypedContractMethod<
    [
      familyArbadId: BigNumberish,
      amount: BigNumberish,
      durationDays: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "borrowOrg"
  ): TypedContractMethod<
    [
      orgArbadId: BigNumberish,
      amount: BigNumberish,
      durationDays: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "familyCreditLines"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint
      ] & {
        arbadId: bigint;
        creditType: bigint;
        creditRating: bigint;
        creditLimit: bigint;
        borrowed: bigint;
        totalBorrowed: bigint;
        totalRepaid: bigint;
        defaultCount: bigint;
        onTimeCount: bigint;
        isActive: boolean;
        openedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "familyLoans"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean
      ] & {
        loanId: bigint;
        arbadId: bigint;
        creditType: bigint;
        principal: bigint;
        interest: bigint;
        dueDate: bigint;
        borrowedAt: bigint;
        repaidAt: bigint;
        active: boolean;
        defaulted: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getFamilyCreditLine"
  ): TypedContractMethod<
    [arbadId: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, boolean] & {
        rating: bigint;
        limit: bigint;
        borrowed: bigint;
        available: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getOrgCreditLine"
  ): TypedContractMethod<
    [arbadId: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, boolean] & {
        rating: bigint;
        limit: bigint;
        borrowed: bigint;
        available: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasFamilyCreditLine"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "hasOrgCreditLine"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "interestRateBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "nextLoanId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "openFamilyCreditLine"
  ): TypedContractMethod<[familyArbadId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "openOrgCreditLine"
  ): TypedContractMethod<[orgArbadId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "orgCreditLines"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint
      ] & {
        arbadId: bigint;
        creditType: bigint;
        creditRating: bigint;
        creditLimit: bigint;
        borrowed: bigint;
        totalBorrowed: bigint;
        totalRepaid: bigint;
        defaultCount: bigint;
        onTimeCount: bigint;
        isActive: boolean;
        openedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "orgLoans"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean
      ] & {
        loanId: bigint;
        arbadId: bigint;
        creditType: bigint;
        principal: bigint;
        interest: bigint;
        dueDate: bigint;
        borrowedAt: bigint;
        repaidAt: bigint;
        active: boolean;
        defaulted: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "repayFamily"
  ): TypedContractMethod<
    [familyArbadId: BigNumberish, loanIdx: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "repayOrg"
  ): TypedContractMethod<
    [orgArbadId: BigNumberish, loanIdx: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setInterestRate"
  ): TypedContractMethod<[rateBps: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "CreditLineOpened"
  ): TypedContractEvent<
    CreditLineOpenedEvent.InputTuple,
    CreditLineOpenedEvent.OutputTuple,
    CreditLineOpenedEvent.OutputObject
  >;
  getEvent(
    key: "InterestRateUpdated"
  ): TypedContractEvent<
    InterestRateUpdatedEvent.InputTuple,
    InterestRateUpdatedEvent.OutputTuple,
    InterestRateUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "LoanRepaid"
  ): TypedContractEvent<
    LoanRepaidEvent.InputTuple,
    LoanRepaidEvent.OutputTuple,
    LoanRepaidEvent.OutputObject
  >;
  getEvent(
    key: "LoanTaken"
  ): TypedContractEvent<
    LoanTakenEvent.InputTuple,
    LoanTakenEvent.OutputTuple,
    LoanTakenEvent.OutputObject
  >;
  getEvent(
    key: "OwnerChanged"
  ): TypedContractEvent<
    OwnerChangedEvent.InputTuple,
    OwnerChangedEvent.OutputTuple,
    OwnerChangedEvent.OutputObject
  >;
  getEvent(
    key: "RatingUpdated"
  ): TypedContractEvent<
    RatingUpdatedEvent.InputTuple,
    RatingUpdatedEvent.OutputTuple,
    RatingUpdatedEvent.OutputObject
  >;

  filters: {
    "CreditLineOpened(uint256,uint8,uint256)": TypedContractEvent<
      CreditLineOpenedEvent.InputTuple,
      CreditLineOpenedEvent.OutputTuple,
      CreditLineOpenedEvent.OutputObject
    >;
    CreditLineOpened: TypedContractEvent<
      CreditLineOpenedEvent.InputTuple,
      CreditLineOpenedEvent.OutputTuple,
      CreditLineOpenedEvent.OutputObject
    >;

    "InterestRateUpdated(uint256,uint256)": TypedContractEvent<
      InterestRateUpdatedEvent.InputTuple,
      InterestRateUpdatedEvent.OutputTuple,
      InterestRateUpdatedEvent.OutputObject
    >;
    InterestRateUpdated: TypedContractEvent<
      InterestRateUpdatedEvent.InputTuple,
      InterestRateUpdatedEvent.OutputTuple,
      InterestRateUpdatedEvent.OutputObject
    >;

    "LoanRepaid(uint256,uint256,uint8,bool)": TypedContractEvent<
      LoanRepaidEvent.InputTuple,
      LoanRepaidEvent.OutputTuple,
      LoanRepaidEvent.OutputObject
    >;
    LoanRepaid: TypedContractEvent<
      LoanRepaidEvent.InputTuple,
      LoanRepaidEvent.OutputTuple,
      LoanRepaidEvent.OutputObject
    >;

    "LoanTaken(uint256,uint256,uint8,uint256)": TypedContractEvent<
      LoanTakenEvent.InputTuple,
      LoanTakenEvent.OutputTuple,
      LoanTakenEvent.OutputObject
    >;
    LoanTaken: TypedContractEvent<
      LoanTakenEvent.InputTuple,
      LoanTakenEvent.OutputTuple,
      LoanTakenEvent.OutputObject
    >;

    "OwnerChanged(address,address)": TypedContractEvent<
      OwnerChangedEvent.InputTuple,
      OwnerChangedEvent.OutputTuple,
      OwnerChangedEvent.OutputObject
    >;
    OwnerChanged: TypedContractEvent<
      OwnerChangedEvent.InputTuple,
      OwnerChangedEvent.OutputTuple,
      OwnerChangedEvent.OutputObject
    >;

    "RatingUpdated(uint256,uint8,uint256)": TypedContractEvent<
      RatingUpdatedEvent.InputTuple,
      RatingUpdatedEvent.OutputTuple,
      RatingUpdatedEvent.OutputObject
    >;
    RatingUpdated: TypedContractEvent<
      RatingUpdatedEvent.InputTuple,
      RatingUpdatedEvent.OutputTuple,
      RatingUpdatedEvent.OutputObject
    >;
  };
}
