/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface ArbadCompletionInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "INITIAL_ORG_SIZE"
      | "KHURAL_AGE_LIMIT"
      | "MAX_ORG_MEMBERS"
      | "addChild"
      | "addOrgMember"
      | "changeHeir"
      | "childCreatesOwnArbad"
      | "createDepartment"
      | "createOrganizationalArbad"
      | "familyArbads"
      | "formScientificCouncil"
      | "formZun"
      | "getArbadTypeForSeat"
      | "getFamilyArbad"
      | "getKhuralRepresentatives"
      | "getOrgArbad"
      | "getZun"
      | "isEligibleForTier2"
      | "isEligibleForTier3"
      | "isMarried"
      | "isValidKhuralRepresentative"
      | "nextFamilyArbadId"
      | "nextOrgArbadId"
      | "nextZunId"
      | "orgArbads"
      | "owner"
      | "registerMarriage"
      | "scientificCouncilId"
      | "seatToFamilyArbad"
      | "seatToOrgArbad"
      | "setKhuralRepresentative"
      | "setOrgLeader"
      | "setZunElder"
      | "totalFamilyArbads"
      | "totalOrgArbads"
      | "transferOwnership"
      | "zuns"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ArbadJoinedZun"
      | "ChildAdded"
      | "ChildCreatedOwnArbad"
      | "DepartmentCreated"
      | "HeirChanged"
      | "HeirSet"
      | "KhuralRepresentativeSet"
      | "MarriageRegistered"
      | "OrgArbadCreated"
      | "OrgLeaderSet"
      | "OrgMemberAdded"
      | "OrgMemberRemoved"
      | "OwnerChanged"
      | "ScientificCouncilFormed"
      | "ZunElderSet"
      | "ZunFormed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "INITIAL_ORG_SIZE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "KHURAL_AGE_LIMIT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_ORG_MEMBERS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addChild",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "addOrgMember",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "changeHeir",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "childCreatesOwnArbad",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createDepartment",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "createOrganizationalArbad",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "familyArbads",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "formScientificCouncil",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "formZun",
    values: [string, BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getArbadTypeForSeat",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getFamilyArbad",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getKhuralRepresentatives",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getOrgArbad",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getZun",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isEligibleForTier2",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isEligibleForTier3",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isMarried",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isValidKhuralRepresentative",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nextFamilyArbadId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nextOrgArbadId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "nextZunId", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "orgArbads",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerMarriage",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "scientificCouncilId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "seatToFamilyArbad",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "seatToOrgArbad",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setKhuralRepresentative",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setOrgLeader",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setZunElder",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalFamilyArbads",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalOrgArbads",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "zuns", values: [BigNumberish]): string;

  decodeFunctionResult(
    functionFragment: "INITIAL_ORG_SIZE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "KHURAL_AGE_LIMIT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_ORG_MEMBERS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addChild", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "addOrgMember",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "changeHeir", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "childCreatesOwnArbad",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createDepartment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createOrganizationalArbad",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "familyArbads",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "formScientificCouncil",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "formZun", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getArbadTypeForSeat",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFamilyArbad",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getKhuralRepresentatives",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOrgArbad",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getZun", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isEligibleForTier2",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isEligibleForTier3",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isMarried", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isValidKhuralRepresentative",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextFamilyArbadId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextOrgArbadId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "nextZunId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "orgArbads", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerMarriage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "scientificCouncilId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "seatToFamilyArbad",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "seatToOrgArbad",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setKhuralRepresentative",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setOrgLeader",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setZunElder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalFamilyArbads",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalOrgArbads",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "zuns", data: BytesLike): Result;
}

export namespace ArbadJoinedZunEvent {
  export type InputTuple = [zunId: BigNumberish, arbadId: BigNumberish];
  export type OutputTuple = [zunId: bigint, arbadId: bigint];
  export interface OutputObject {
    zunId: bigint;
    arbadId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ChildAddedEvent {
  export type InputTuple = [arbadId: BigNumberish, childSeatId: BigNumberish];
  export type OutputTuple = [arbadId: bigint, childSeatId: bigint];
  export interface OutputObject {
    arbadId: bigint;
    childSeatId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ChildCreatedOwnArbadEvent {
  export type InputTuple = [
    parentArbadId: BigNumberish,
    newArbadId: BigNumberish,
    childSeatId: BigNumberish
  ];
  export type OutputTuple = [
    parentArbadId: bigint,
    newArbadId: bigint,
    childSeatId: bigint
  ];
  export interface OutputObject {
    parentArbadId: bigint;
    newArbadId: bigint;
    childSeatId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepartmentCreatedEvent {
  export type InputTuple = [
    parentId: BigNumberish,
    deptId: BigNumberish,
    name: string
  ];
  export type OutputTuple = [parentId: bigint, deptId: bigint, name: string];
  export interface OutputObject {
    parentId: bigint;
    deptId: bigint;
    name: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace HeirChangedEvent {
  export type InputTuple = [
    arbadId: BigNumberish,
    oldHeirSeatId: BigNumberish,
    newHeirSeatId: BigNumberish
  ];
  export type OutputTuple = [
    arbadId: bigint,
    oldHeirSeatId: bigint,
    newHeirSeatId: bigint
  ];
  export interface OutputObject {
    arbadId: bigint;
    oldHeirSeatId: bigint;
    newHeirSeatId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace HeirSetEvent {
  export type InputTuple = [arbadId: BigNumberish, heirSeatId: BigNumberish];
  export type OutputTuple = [arbadId: bigint, heirSeatId: bigint];
  export interface OutputObject {
    arbadId: bigint;
    heirSeatId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace KhuralRepresentativeSetEvent {
  export type InputTuple = [
    arbadId: BigNumberish,
    repSeatId: BigNumberish,
    birthYear: BigNumberish
  ];
  export type OutputTuple = [
    arbadId: bigint,
    repSeatId: bigint,
    birthYear: bigint
  ];
  export interface OutputObject {
    arbadId: bigint;
    repSeatId: bigint;
    birthYear: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MarriageRegisteredEvent {
  export type InputTuple = [
    arbadId: BigNumberish,
    husbandSeatId: BigNumberish,
    wifeSeatId: BigNumberish
  ];
  export type OutputTuple = [
    arbadId: bigint,
    husbandSeatId: bigint,
    wifeSeatId: bigint
  ];
  export interface OutputObject {
    arbadId: bigint;
    husbandSeatId: bigint;
    wifeSeatId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrgArbadCreatedEvent {
  export type InputTuple = [
    arbadId: BigNumberish,
    name: string,
    orgType: BigNumberish,
    branch: BigNumberish
  ];
  export type OutputTuple = [
    arbadId: bigint,
    name: string,
    orgType: bigint,
    branch: bigint
  ];
  export interface OutputObject {
    arbadId: bigint;
    name: string;
    orgType: bigint;
    branch: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrgLeaderSetEvent {
  export type InputTuple = [arbadId: BigNumberish, leaderSeatId: BigNumberish];
  export type OutputTuple = [arbadId: bigint, leaderSeatId: bigint];
  export interface OutputObject {
    arbadId: bigint;
    leaderSeatId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrgMemberAddedEvent {
  export type InputTuple = [arbadId: BigNumberish, seatId: BigNumberish];
  export type OutputTuple = [arbadId: bigint, seatId: bigint];
  export interface OutputObject {
    arbadId: bigint;
    seatId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrgMemberRemovedEvent {
  export type InputTuple = [arbadId: BigNumberish, seatId: BigNumberish];
  export type OutputTuple = [arbadId: bigint, seatId: bigint];
  export interface OutputObject {
    arbadId: bigint;
    seatId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnerChangedEvent {
  export type InputTuple = [oldOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [oldOwner: string, newOwner: string];
  export interface OutputObject {
    oldOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ScientificCouncilFormedEvent {
  export type InputTuple = [councilId: BigNumberish];
  export type OutputTuple = [councilId: bigint];
  export interface OutputObject {
    councilId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ZunElderSetEvent {
  export type InputTuple = [zunId: BigNumberish, elderSeatId: BigNumberish];
  export type OutputTuple = [zunId: bigint, elderSeatId: bigint];
  export interface OutputObject {
    zunId: bigint;
    elderSeatId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ZunFormedEvent {
  export type InputTuple = [
    zunId: BigNumberish,
    name: string,
    arbadIds: BigNumberish[]
  ];
  export type OutputTuple = [zunId: bigint, name: string, arbadIds: bigint[]];
  export interface OutputObject {
    zunId: bigint;
    name: string;
    arbadIds: bigint[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ArbadCompletion extends BaseContract {
  connect(runner?: ContractRunner | null): ArbadCompletion;
  waitForDeployment(): Promise<this>;

  interface: ArbadCompletionInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  INITIAL_ORG_SIZE: TypedContractMethod<[], [bigint], "view">;

  KHURAL_AGE_LIMIT: TypedContractMethod<[], [bigint], "view">;

  MAX_ORG_MEMBERS: TypedContractMethod<[], [bigint], "view">;

  addChild: TypedContractMethod<
    [arbadId: BigNumberish, childSeatId: BigNumberish],
    [void],
    "nonpayable"
  >;

  addOrgMember: TypedContractMethod<
    [arbadId: BigNumberish, seatId: BigNumberish],
    [void],
    "nonpayable"
  >;

  changeHeir: TypedContractMethod<
    [arbadId: BigNumberish, newHeirSeatId: BigNumberish],
    [void],
    "nonpayable"
  >;

  childCreatesOwnArbad: TypedContractMethod<
    [
      parentArbadId: BigNumberish,
      childSeatId: BigNumberish,
      spouseSeatId: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  createDepartment: TypedContractMethod<
    [parentOrgId: BigNumberish, deptName: string],
    [bigint],
    "nonpayable"
  >;

  createOrganizationalArbad: TypedContractMethod<
    [name: string, orgType: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  familyArbads: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint
      ] & {
        arbadId: bigint;
        husbandSeatId: bigint;
        wifeSeatId: bigint;
        heirSeatId: bigint;
        zunId: bigint;
        khuralRepSeatId: bigint;
        khuralRepBirthYear: bigint;
        isActive: boolean;
        createdAt: bigint;
      }
    ],
    "view"
  >;

  formScientificCouncil: TypedContractMethod<
    [name: string],
    [bigint],
    "nonpayable"
  >;

  formZun: TypedContractMethod<
    [zunName: string, arbadIds: BigNumberish[]],
    [bigint],
    "nonpayable"
  >;

  getArbadTypeForSeat: TypedContractMethod<
    [seatId: BigNumberish],
    [[bigint, bigint] & { arbadType: bigint; arbadId: bigint }],
    "view"
  >;

  getFamilyArbad: TypedContractMethod<
    [arbadId: BigNumberish],
    [
      [bigint, bigint, bigint[], bigint, bigint, bigint, boolean] & {
        husbandSeatId: bigint;
        wifeSeatId: bigint;
        childrenSeatIds: bigint[];
        heirSeatId: bigint;
        zunId: bigint;
        khuralRepSeatId: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  getKhuralRepresentatives: TypedContractMethod<[], [bigint[]], "view">;

  getOrgArbad: TypedContractMethod<
    [arbadId: BigNumberish],
    [
      [string, bigint[], bigint, bigint, bigint, boolean] & {
        name: string;
        memberSeatIds: bigint[];
        leaderSeatId: bigint;
        orgType: bigint;
        powerBranch: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  getZun: TypedContractMethod<
    [zunId: BigNumberish],
    [
      [string, bigint, bigint[], bigint, boolean] & {
        name: string;
        founderArbadId: bigint;
        memberArbadIds: bigint[];
        elderSeatId: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  isEligibleForTier2: TypedContractMethod<
    [seatId: BigNumberish],
    [boolean],
    "view"
  >;

  isEligibleForTier3: TypedContractMethod<
    [seatId: BigNumberish],
    [boolean],
    "view"
  >;

  isMarried: TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;

  isValidKhuralRepresentative: TypedContractMethod<
    [arbadId: BigNumberish, seatId: BigNumberish],
    [boolean],
    "view"
  >;

  nextFamilyArbadId: TypedContractMethod<[], [bigint], "view">;

  nextOrgArbadId: TypedContractMethod<[], [bigint], "view">;

  nextZunId: TypedContractMethod<[], [bigint], "view">;

  orgArbads: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, bigint, bigint, bigint, boolean, bigint] & {
        arbadId: bigint;
        name: string;
        leaderSeatId: bigint;
        orgType: bigint;
        powerBranch: bigint;
        parentOrgId: bigint;
        isActive: boolean;
        createdAt: bigint;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  registerMarriage: TypedContractMethod<
    [husbandSeatId: BigNumberish, wifeSeatId: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  scientificCouncilId: TypedContractMethod<[], [bigint], "view">;

  seatToFamilyArbad: TypedContractMethod<
    [arg0: BigNumberish],
    [bigint],
    "view"
  >;

  seatToOrgArbad: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  setKhuralRepresentative: TypedContractMethod<
    [arbadId: BigNumberish, repSeatId: BigNumberish, birthYear: BigNumberish],
    [void],
    "nonpayable"
  >;

  setOrgLeader: TypedContractMethod<
    [arbadId: BigNumberish, leaderSeatId: BigNumberish],
    [void],
    "nonpayable"
  >;

  setZunElder: TypedContractMethod<
    [zunId: BigNumberish, elderSeatId: BigNumberish],
    [void],
    "nonpayable"
  >;

  totalFamilyArbads: TypedContractMethod<[], [bigint], "view">;

  totalOrgArbads: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  zuns: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, bigint, boolean, bigint] & {
        zunId: bigint;
        name: string;
        founderArbadId: bigint;
        elderSeatId: bigint;
        isActive: boolean;
        createdAt: bigint;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "INITIAL_ORG_SIZE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "KHURAL_AGE_LIMIT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_ORG_MEMBERS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "addChild"
  ): TypedContractMethod<
    [arbadId: BigNumberish, childSeatId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addOrgMember"
  ): TypedContractMethod<
    [arbadId: BigNumberish, seatId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "changeHeir"
  ): TypedContractMethod<
    [arbadId: BigNumberish, newHeirSeatId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "childCreatesOwnArbad"
  ): TypedContractMethod<
    [
      parentArbadId: BigNumberish,
      childSeatId: BigNumberish,
      spouseSeatId: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createDepartment"
  ): TypedContractMethod<
    [parentOrgId: BigNumberish, deptName: string],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createOrganizationalArbad"
  ): TypedContractMethod<
    [name: string, orgType: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "familyArbads"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint
      ] & {
        arbadId: bigint;
        husbandSeatId: bigint;
        wifeSeatId: bigint;
        heirSeatId: bigint;
        zunId: bigint;
        khuralRepSeatId: bigint;
        khuralRepBirthYear: bigint;
        isActive: boolean;
        createdAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "formScientificCouncil"
  ): TypedContractMethod<[name: string], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "formZun"
  ): TypedContractMethod<
    [zunName: string, arbadIds: BigNumberish[]],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getArbadTypeForSeat"
  ): TypedContractMethod<
    [seatId: BigNumberish],
    [[bigint, bigint] & { arbadType: bigint; arbadId: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getFamilyArbad"
  ): TypedContractMethod<
    [arbadId: BigNumberish],
    [
      [bigint, bigint, bigint[], bigint, bigint, bigint, boolean] & {
        husbandSeatId: bigint;
        wifeSeatId: bigint;
        childrenSeatIds: bigint[];
        heirSeatId: bigint;
        zunId: bigint;
        khuralRepSeatId: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getKhuralRepresentatives"
  ): TypedContractMethod<[], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getOrgArbad"
  ): TypedContractMethod<
    [arbadId: BigNumberish],
    [
      [string, bigint[], bigint, bigint, bigint, boolean] & {
        name: string;
        memberSeatIds: bigint[];
        leaderSeatId: bigint;
        orgType: bigint;
        powerBranch: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getZun"
  ): TypedContractMethod<
    [zunId: BigNumberish],
    [
      [string, bigint, bigint[], bigint, boolean] & {
        name: string;
        founderArbadId: bigint;
        memberArbadIds: bigint[];
        elderSeatId: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "isEligibleForTier2"
  ): TypedContractMethod<[seatId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "isEligibleForTier3"
  ): TypedContractMethod<[seatId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "isMarried"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "isValidKhuralRepresentative"
  ): TypedContractMethod<
    [arbadId: BigNumberish, seatId: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "nextFamilyArbadId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "nextOrgArbadId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "nextZunId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "orgArbads"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, bigint, bigint, bigint, boolean, bigint] & {
        arbadId: bigint;
        name: string;
        leaderSeatId: bigint;
        orgType: bigint;
        powerBranch: bigint;
        parentOrgId: bigint;
        isActive: boolean;
        createdAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerMarriage"
  ): TypedContractMethod<
    [husbandSeatId: BigNumberish, wifeSeatId: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "scientificCouncilId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "seatToFamilyArbad"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "seatToOrgArbad"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "setKhuralRepresentative"
  ): TypedContractMethod<
    [arbadId: BigNumberish, repSeatId: BigNumberish, birthYear: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setOrgLeader"
  ): TypedContractMethod<
    [arbadId: BigNumberish, leaderSeatId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setZunElder"
  ): TypedContractMethod<
    [zunId: BigNumberish, elderSeatId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "totalFamilyArbads"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalOrgArbads"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "zuns"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, bigint, boolean, bigint] & {
        zunId: bigint;
        name: string;
        founderArbadId: bigint;
        elderSeatId: bigint;
        isActive: boolean;
        createdAt: bigint;
      }
    ],
    "view"
  >;

  getEvent(
    key: "ArbadJoinedZun"
  ): TypedContractEvent<
    ArbadJoinedZunEvent.InputTuple,
    ArbadJoinedZunEvent.OutputTuple,
    ArbadJoinedZunEvent.OutputObject
  >;
  getEvent(
    key: "ChildAdded"
  ): TypedContractEvent<
    ChildAddedEvent.InputTuple,
    ChildAddedEvent.OutputTuple,
    ChildAddedEvent.OutputObject
  >;
  getEvent(
    key: "ChildCreatedOwnArbad"
  ): TypedContractEvent<
    ChildCreatedOwnArbadEvent.InputTuple,
    ChildCreatedOwnArbadEvent.OutputTuple,
    ChildCreatedOwnArbadEvent.OutputObject
  >;
  getEvent(
    key: "DepartmentCreated"
  ): TypedContractEvent<
    DepartmentCreatedEvent.InputTuple,
    DepartmentCreatedEvent.OutputTuple,
    DepartmentCreatedEvent.OutputObject
  >;
  getEvent(
    key: "HeirChanged"
  ): TypedContractEvent<
    HeirChangedEvent.InputTuple,
    HeirChangedEvent.OutputTuple,
    HeirChangedEvent.OutputObject
  >;
  getEvent(
    key: "HeirSet"
  ): TypedContractEvent<
    HeirSetEvent.InputTuple,
    HeirSetEvent.OutputTuple,
    HeirSetEvent.OutputObject
  >;
  getEvent(
    key: "KhuralRepresentativeSet"
  ): TypedContractEvent<
    KhuralRepresentativeSetEvent.InputTuple,
    KhuralRepresentativeSetEvent.OutputTuple,
    KhuralRepresentativeSetEvent.OutputObject
  >;
  getEvent(
    key: "MarriageRegistered"
  ): TypedContractEvent<
    MarriageRegisteredEvent.InputTuple,
    MarriageRegisteredEvent.OutputTuple,
    MarriageRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "OrgArbadCreated"
  ): TypedContractEvent<
    OrgArbadCreatedEvent.InputTuple,
    OrgArbadCreatedEvent.OutputTuple,
    OrgArbadCreatedEvent.OutputObject
  >;
  getEvent(
    key: "OrgLeaderSet"
  ): TypedContractEvent<
    OrgLeaderSetEvent.InputTuple,
    OrgLeaderSetEvent.OutputTuple,
    OrgLeaderSetEvent.OutputObject
  >;
  getEvent(
    key: "OrgMemberAdded"
  ): TypedContractEvent<
    OrgMemberAddedEvent.InputTuple,
    OrgMemberAddedEvent.OutputTuple,
    OrgMemberAddedEvent.OutputObject
  >;
  getEvent(
    key: "OrgMemberRemoved"
  ): TypedContractEvent<
    OrgMemberRemovedEvent.InputTuple,
    OrgMemberRemovedEvent.OutputTuple,
    OrgMemberRemovedEvent.OutputObject
  >;
  getEvent(
    key: "OwnerChanged"
  ): TypedContractEvent<
    OwnerChangedEvent.InputTuple,
    OwnerChangedEvent.OutputTuple,
    OwnerChangedEvent.OutputObject
  >;
  getEvent(
    key: "ScientificCouncilFormed"
  ): TypedContractEvent<
    ScientificCouncilFormedEvent.InputTuple,
    ScientificCouncilFormedEvent.OutputTuple,
    ScientificCouncilFormedEvent.OutputObject
  >;
  getEvent(
    key: "ZunElderSet"
  ): TypedContractEvent<
    ZunElderSetEvent.InputTuple,
    ZunElderSetEvent.OutputTuple,
    ZunElderSetEvent.OutputObject
  >;
  getEvent(
    key: "ZunFormed"
  ): TypedContractEvent<
    ZunFormedEvent.InputTuple,
    ZunFormedEvent.OutputTuple,
    ZunFormedEvent.OutputObject
  >;

  filters: {
    "ArbadJoinedZun(uint256,uint256)": TypedContractEvent<
      ArbadJoinedZunEvent.InputTuple,
      ArbadJoinedZunEvent.OutputTuple,
      ArbadJoinedZunEvent.OutputObject
    >;
    ArbadJoinedZun: TypedContractEvent<
      ArbadJoinedZunEvent.InputTuple,
      ArbadJoinedZunEvent.OutputTuple,
      ArbadJoinedZunEvent.OutputObject
    >;

    "ChildAdded(uint256,uint256)": TypedContractEvent<
      ChildAddedEvent.InputTuple,
      ChildAddedEvent.OutputTuple,
      ChildAddedEvent.OutputObject
    >;
    ChildAdded: TypedContractEvent<
      ChildAddedEvent.InputTuple,
      ChildAddedEvent.OutputTuple,
      ChildAddedEvent.OutputObject
    >;

    "ChildCreatedOwnArbad(uint256,uint256,uint256)": TypedContractEvent<
      ChildCreatedOwnArbadEvent.InputTuple,
      ChildCreatedOwnArbadEvent.OutputTuple,
      ChildCreatedOwnArbadEvent.OutputObject
    >;
    ChildCreatedOwnArbad: TypedContractEvent<
      ChildCreatedOwnArbadEvent.InputTuple,
      ChildCreatedOwnArbadEvent.OutputTuple,
      ChildCreatedOwnArbadEvent.OutputObject
    >;

    "DepartmentCreated(uint256,uint256,string)": TypedContractEvent<
      DepartmentCreatedEvent.InputTuple,
      DepartmentCreatedEvent.OutputTuple,
      DepartmentCreatedEvent.OutputObject
    >;
    DepartmentCreated: TypedContractEvent<
      DepartmentCreatedEvent.InputTuple,
      DepartmentCreatedEvent.OutputTuple,
      DepartmentCreatedEvent.OutputObject
    >;

    "HeirChanged(uint256,uint256,uint256)": TypedContractEvent<
      HeirChangedEvent.InputTuple,
      HeirChangedEvent.OutputTuple,
      HeirChangedEvent.OutputObject
    >;
    HeirChanged: TypedContractEvent<
      HeirChangedEvent.InputTuple,
      HeirChangedEvent.OutputTuple,
      HeirChangedEvent.OutputObject
    >;

    "HeirSet(uint256,uint256)": TypedContractEvent<
      HeirSetEvent.InputTuple,
      HeirSetEvent.OutputTuple,
      HeirSetEvent.OutputObject
    >;
    HeirSet: TypedContractEvent<
      HeirSetEvent.InputTuple,
      HeirSetEvent.OutputTuple,
      HeirSetEvent.OutputObject
    >;

    "KhuralRepresentativeSet(uint256,uint256,uint64)": TypedContractEvent<
      KhuralRepresentativeSetEvent.InputTuple,
      KhuralRepresentativeSetEvent.OutputTuple,
      KhuralRepresentativeSetEvent.OutputObject
    >;
    KhuralRepresentativeSet: TypedContractEvent<
      KhuralRepresentativeSetEvent.InputTuple,
      KhuralRepresentativeSetEvent.OutputTuple,
      KhuralRepresentativeSetEvent.OutputObject
    >;

    "MarriageRegistered(uint256,uint256,uint256)": TypedContractEvent<
      MarriageRegisteredEvent.InputTuple,
      MarriageRegisteredEvent.OutputTuple,
      MarriageRegisteredEvent.OutputObject
    >;
    MarriageRegistered: TypedContractEvent<
      MarriageRegisteredEvent.InputTuple,
      MarriageRegisteredEvent.OutputTuple,
      MarriageRegisteredEvent.OutputObject
    >;

    "OrgArbadCreated(uint256,string,uint8,uint8)": TypedContractEvent<
      OrgArbadCreatedEvent.InputTuple,
      OrgArbadCreatedEvent.OutputTuple,
      OrgArbadCreatedEvent.OutputObject
    >;
    OrgArbadCreated: TypedContractEvent<
      OrgArbadCreatedEvent.InputTuple,
      OrgArbadCreatedEvent.OutputTuple,
      OrgArbadCreatedEvent.OutputObject
    >;

    "OrgLeaderSet(uint256,uint256)": TypedContractEvent<
      OrgLeaderSetEvent.InputTuple,
      OrgLeaderSetEvent.OutputTuple,
      OrgLeaderSetEvent.OutputObject
    >;
    OrgLeaderSet: TypedContractEvent<
      OrgLeaderSetEvent.InputTuple,
      OrgLeaderSetEvent.OutputTuple,
      OrgLeaderSetEvent.OutputObject
    >;

    "OrgMemberAdded(uint256,uint256)": TypedContractEvent<
      OrgMemberAddedEvent.InputTuple,
      OrgMemberAddedEvent.OutputTuple,
      OrgMemberAddedEvent.OutputObject
    >;
    OrgMemberAdded: TypedContractEvent<
      OrgMemberAddedEvent.InputTuple,
      OrgMemberAddedEvent.OutputTuple,
      OrgMemberAddedEvent.OutputObject
    >;

    "OrgMemberRemoved(uint256,uint256)": TypedContractEvent<
      OrgMemberRemovedEvent.InputTuple,
      OrgMemberRemovedEvent.OutputTuple,
      OrgMemberRemovedEvent.OutputObject
    >;
    OrgMemberRemoved: TypedContractEvent<
      OrgMemberRemovedEvent.InputTuple,
      OrgMemberRemovedEvent.OutputTuple,
      OrgMemberRemovedEvent.OutputObject
    >;

    "OwnerChanged(address,address)": TypedContractEvent<
      OwnerChangedEvent.InputTuple,
      OwnerChangedEvent.OutputTuple,
      OwnerChangedEvent.OutputObject
    >;
    OwnerChanged: TypedContractEvent<
      OwnerChangedEvent.InputTuple,
      OwnerChangedEvent.OutputTuple,
      OwnerChangedEvent.OutputObject
    >;

    "ScientificCouncilFormed(uint256)": TypedContractEvent<
      ScientificCouncilFormedEvent.InputTuple,
      ScientificCouncilFormedEvent.OutputTuple,
      ScientificCouncilFormedEvent.OutputObject
    >;
    ScientificCouncilFormed: TypedContractEvent<
      ScientificCouncilFormedEvent.InputTuple,
      ScientificCouncilFormedEvent.OutputTuple,
      ScientificCouncilFormedEvent.OutputObject
    >;

    "ZunElderSet(uint256,uint256)": TypedContractEvent<
      ZunElderSetEvent.InputTuple,
      ZunElderSetEvent.OutputTuple,
      ZunElderSetEvent.OutputObject
    >;
    ZunElderSet: TypedContractEvent<
      ZunElderSetEvent.InputTuple,
      ZunElderSetEvent.OutputTuple,
      ZunElderSetEvent.OutputObject
    >;

    "ZunFormed(uint256,string,uint256[])": TypedContractEvent<
      ZunFormedEvent.InputTuple,
      ZunFormedEvent.OutputTuple,
      ZunFormedEvent.OutputObject
    >;
    ZunFormed: TypedContractEvent<
      ZunFormedEvent.InputTuple,
      ZunFormedEvent.OutputTuple,
      ZunFormedEvent.OutputObject
    >;
  };
}
