/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface ArbanCompletionInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "INITIAL_ORG_SIZE"
      | "KHURAL_AGE_LIMIT"
      | "MAX_ORG_MEMBERS"
      | "addChild"
      | "addOrgMember"
      | "changeHeir"
      | "childCreatesOwnArban"
      | "createDepartment"
      | "createOrganizationalArban"
      | "familyArbans"
      | "formScientificCouncil"
      | "formZun"
      | "getArbanTypeForSeat"
      | "getFamilyArban"
      | "getKhuralRepresentatives"
      | "getOrgArban"
      | "getZun"
      | "isEligibleForTier2"
      | "isEligibleForTier3"
      | "isMarried"
      | "isValidKhuralRepresentative"
      | "nextFamilyArbanId"
      | "nextOrgArbanId"
      | "nextZunId"
      | "orgArbans"
      | "owner"
      | "registerMarriage"
      | "scientificCouncilId"
      | "seatToFamilyArban"
      | "seatToOrgArban"
      | "setKhuralRepresentative"
      | "setOrgLeader"
      | "setZunElder"
      | "totalFamilyArbans"
      | "totalOrgArbans"
      | "transferOwnership"
      | "zuns"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ArbanJoinedZun"
      | "ChildAdded"
      | "ChildCreatedOwnArban"
      | "DepartmentCreated"
      | "HeirChanged"
      | "HeirSet"
      | "KhuralRepresentativeSet"
      | "MarriageRegistered"
      | "OrgArbanCreated"
      | "OrgLeaderSet"
      | "OrgMemberAdded"
      | "OrgMemberRemoved"
      | "OwnerChanged"
      | "ScientificCouncilFormed"
      | "ZunElderSet"
      | "ZunFormed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "INITIAL_ORG_SIZE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "KHURAL_AGE_LIMIT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_ORG_MEMBERS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addChild",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "addOrgMember",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "changeHeir",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "childCreatesOwnArban",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createDepartment",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "createOrganizationalArban",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "familyArbans",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "formScientificCouncil",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "formZun",
    values: [string, BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getArbanTypeForSeat",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getFamilyArban",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getKhuralRepresentatives",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getOrgArban",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getZun",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isEligibleForTier2",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isEligibleForTier3",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isMarried",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isValidKhuralRepresentative",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nextFamilyArbanId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nextOrgArbanId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "nextZunId", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "orgArbans",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerMarriage",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "scientificCouncilId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "seatToFamilyArban",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "seatToOrgArban",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setKhuralRepresentative",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setOrgLeader",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setZunElder",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalFamilyArbans",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalOrgArbans",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "zuns", values: [BigNumberish]): string;

  decodeFunctionResult(
    functionFragment: "INITIAL_ORG_SIZE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "KHURAL_AGE_LIMIT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_ORG_MEMBERS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addChild", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "addOrgMember",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "changeHeir", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "childCreatesOwnArban",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createDepartment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createOrganizationalArban",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "familyArbans",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "formScientificCouncil",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "formZun", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getArbanTypeForSeat",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFamilyArban",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getKhuralRepresentatives",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOrgArban",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getZun", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isEligibleForTier2",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isEligibleForTier3",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isMarried", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isValidKhuralRepresentative",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextFamilyArbanId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextOrgArbanId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "nextZunId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "orgArbans", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerMarriage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "scientificCouncilId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "seatToFamilyArban",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "seatToOrgArban",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setKhuralRepresentative",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setOrgLeader",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setZunElder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalFamilyArbans",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalOrgArbans",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "zuns", data: BytesLike): Result;
}

export namespace ArbanJoinedZunEvent {
  export type InputTuple = [zunId: BigNumberish, arbanId: BigNumberish];
  export type OutputTuple = [zunId: bigint, arbanId: bigint];
  export interface OutputObject {
    zunId: bigint;
    arbanId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ChildAddedEvent {
  export type InputTuple = [arbanId: BigNumberish, childSeatId: BigNumberish];
  export type OutputTuple = [arbanId: bigint, childSeatId: bigint];
  export interface OutputObject {
    arbanId: bigint;
    childSeatId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ChildCreatedOwnArbanEvent {
  export type InputTuple = [
    parentArbanId: BigNumberish,
    newArbanId: BigNumberish,
    childSeatId: BigNumberish
  ];
  export type OutputTuple = [
    parentArbanId: bigint,
    newArbanId: bigint,
    childSeatId: bigint
  ];
  export interface OutputObject {
    parentArbanId: bigint;
    newArbanId: bigint;
    childSeatId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepartmentCreatedEvent {
  export type InputTuple = [
    parentId: BigNumberish,
    deptId: BigNumberish,
    name: string
  ];
  export type OutputTuple = [parentId: bigint, deptId: bigint, name: string];
  export interface OutputObject {
    parentId: bigint;
    deptId: bigint;
    name: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace HeirChangedEvent {
  export type InputTuple = [
    arbanId: BigNumberish,
    oldHeirSeatId: BigNumberish,
    newHeirSeatId: BigNumberish
  ];
  export type OutputTuple = [
    arbanId: bigint,
    oldHeirSeatId: bigint,
    newHeirSeatId: bigint
  ];
  export interface OutputObject {
    arbanId: bigint;
    oldHeirSeatId: bigint;
    newHeirSeatId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace HeirSetEvent {
  export type InputTuple = [arbanId: BigNumberish, heirSeatId: BigNumberish];
  export type OutputTuple = [arbanId: bigint, heirSeatId: bigint];
  export interface OutputObject {
    arbanId: bigint;
    heirSeatId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace KhuralRepresentativeSetEvent {
  export type InputTuple = [
    arbanId: BigNumberish,
    repSeatId: BigNumberish,
    birthYear: BigNumberish
  ];
  export type OutputTuple = [
    arbanId: bigint,
    repSeatId: bigint,
    birthYear: bigint
  ];
  export interface OutputObject {
    arbanId: bigint;
    repSeatId: bigint;
    birthYear: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MarriageRegisteredEvent {
  export type InputTuple = [
    arbanId: BigNumberish,
    husbandSeatId: BigNumberish,
    wifeSeatId: BigNumberish
  ];
  export type OutputTuple = [
    arbanId: bigint,
    husbandSeatId: bigint,
    wifeSeatId: bigint
  ];
  export interface OutputObject {
    arbanId: bigint;
    husbandSeatId: bigint;
    wifeSeatId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrgArbanCreatedEvent {
  export type InputTuple = [
    arbanId: BigNumberish,
    name: string,
    orgType: BigNumberish,
    branch: BigNumberish
  ];
  export type OutputTuple = [
    arbanId: bigint,
    name: string,
    orgType: bigint,
    branch: bigint
  ];
  export interface OutputObject {
    arbanId: bigint;
    name: string;
    orgType: bigint;
    branch: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrgLeaderSetEvent {
  export type InputTuple = [arbanId: BigNumberish, leaderSeatId: BigNumberish];
  export type OutputTuple = [arbanId: bigint, leaderSeatId: bigint];
  export interface OutputObject {
    arbanId: bigint;
    leaderSeatId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrgMemberAddedEvent {
  export type InputTuple = [arbanId: BigNumberish, seatId: BigNumberish];
  export type OutputTuple = [arbanId: bigint, seatId: bigint];
  export interface OutputObject {
    arbanId: bigint;
    seatId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrgMemberRemovedEvent {
  export type InputTuple = [arbanId: BigNumberish, seatId: BigNumberish];
  export type OutputTuple = [arbanId: bigint, seatId: bigint];
  export interface OutputObject {
    arbanId: bigint;
    seatId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnerChangedEvent {
  export type InputTuple = [oldOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [oldOwner: string, newOwner: string];
  export interface OutputObject {
    oldOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ScientificCouncilFormedEvent {
  export type InputTuple = [councilId: BigNumberish];
  export type OutputTuple = [councilId: bigint];
  export interface OutputObject {
    councilId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ZunElderSetEvent {
  export type InputTuple = [zunId: BigNumberish, elderSeatId: BigNumberish];
  export type OutputTuple = [zunId: bigint, elderSeatId: bigint];
  export interface OutputObject {
    zunId: bigint;
    elderSeatId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ZunFormedEvent {
  export type InputTuple = [
    zunId: BigNumberish,
    name: string,
    arbanIds: BigNumberish[]
  ];
  export type OutputTuple = [zunId: bigint, name: string, arbanIds: bigint[]];
  export interface OutputObject {
    zunId: bigint;
    name: string;
    arbanIds: bigint[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ArbanCompletion extends BaseContract {
  connect(runner?: ContractRunner | null): ArbanCompletion;
  waitForDeployment(): Promise<this>;

  interface: ArbanCompletionInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  INITIAL_ORG_SIZE: TypedContractMethod<[], [bigint], "view">;

  KHURAL_AGE_LIMIT: TypedContractMethod<[], [bigint], "view">;

  MAX_ORG_MEMBERS: TypedContractMethod<[], [bigint], "view">;

  addChild: TypedContractMethod<
    [arbanId: BigNumberish, childSeatId: BigNumberish],
    [void],
    "nonpayable"
  >;

  addOrgMember: TypedContractMethod<
    [arbanId: BigNumberish, seatId: BigNumberish],
    [void],
    "nonpayable"
  >;

  changeHeir: TypedContractMethod<
    [arbanId: BigNumberish, newHeirSeatId: BigNumberish],
    [void],
    "nonpayable"
  >;

  childCreatesOwnArban: TypedContractMethod<
    [
      parentArbanId: BigNumberish,
      childSeatId: BigNumberish,
      spouseSeatId: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  createDepartment: TypedContractMethod<
    [parentOrgId: BigNumberish, deptName: string],
    [bigint],
    "nonpayable"
  >;

  createOrganizationalArban: TypedContractMethod<
    [name: string, orgType: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  familyArbans: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint
      ] & {
        arbanId: bigint;
        husbandSeatId: bigint;
        wifeSeatId: bigint;
        heirSeatId: bigint;
        zunId: bigint;
        khuralRepSeatId: bigint;
        khuralRepBirthYear: bigint;
        isActive: boolean;
        createdAt: bigint;
      }
    ],
    "view"
  >;

  formScientificCouncil: TypedContractMethod<
    [name: string],
    [bigint],
    "nonpayable"
  >;

  formZun: TypedContractMethod<
    [zunName: string, arbanIds: BigNumberish[]],
    [bigint],
    "nonpayable"
  >;

  getArbanTypeForSeat: TypedContractMethod<
    [seatId: BigNumberish],
    [[bigint, bigint] & { arbanType: bigint; arbanId: bigint }],
    "view"
  >;

  getFamilyArban: TypedContractMethod<
    [arbanId: BigNumberish],
    [
      [bigint, bigint, bigint[], bigint, bigint, bigint, boolean] & {
        husbandSeatId: bigint;
        wifeSeatId: bigint;
        childrenSeatIds: bigint[];
        heirSeatId: bigint;
        zunId: bigint;
        khuralRepSeatId: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  getKhuralRepresentatives: TypedContractMethod<[], [bigint[]], "view">;

  getOrgArban: TypedContractMethod<
    [arbanId: BigNumberish],
    [
      [string, bigint[], bigint, bigint, bigint, boolean] & {
        name: string;
        memberSeatIds: bigint[];
        leaderSeatId: bigint;
        orgType: bigint;
        powerBranch: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  getZun: TypedContractMethod<
    [zunId: BigNumberish],
    [
      [string, bigint, bigint[], bigint, boolean] & {
        name: string;
        founderArbanId: bigint;
        memberArbanIds: bigint[];
        elderSeatId: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  isEligibleForTier2: TypedContractMethod<
    [seatId: BigNumberish],
    [boolean],
    "view"
  >;

  isEligibleForTier3: TypedContractMethod<
    [seatId: BigNumberish],
    [boolean],
    "view"
  >;

  isMarried: TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;

  isValidKhuralRepresentative: TypedContractMethod<
    [arbanId: BigNumberish, seatId: BigNumberish],
    [boolean],
    "view"
  >;

  nextFamilyArbanId: TypedContractMethod<[], [bigint], "view">;

  nextOrgArbanId: TypedContractMethod<[], [bigint], "view">;

  nextZunId: TypedContractMethod<[], [bigint], "view">;

  orgArbans: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, bigint, bigint, bigint, boolean, bigint] & {
        arbanId: bigint;
        name: string;
        leaderSeatId: bigint;
        orgType: bigint;
        powerBranch: bigint;
        parentOrgId: bigint;
        isActive: boolean;
        createdAt: bigint;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  registerMarriage: TypedContractMethod<
    [husbandSeatId: BigNumberish, wifeSeatId: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  scientificCouncilId: TypedContractMethod<[], [bigint], "view">;

  seatToFamilyArban: TypedContractMethod<
    [arg0: BigNumberish],
    [bigint],
    "view"
  >;

  seatToOrgArban: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  setKhuralRepresentative: TypedContractMethod<
    [arbanId: BigNumberish, repSeatId: BigNumberish, birthYear: BigNumberish],
    [void],
    "nonpayable"
  >;

  setOrgLeader: TypedContractMethod<
    [arbanId: BigNumberish, leaderSeatId: BigNumberish],
    [void],
    "nonpayable"
  >;

  setZunElder: TypedContractMethod<
    [zunId: BigNumberish, elderSeatId: BigNumberish],
    [void],
    "nonpayable"
  >;

  totalFamilyArbans: TypedContractMethod<[], [bigint], "view">;

  totalOrgArbans: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  zuns: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, bigint, boolean, bigint] & {
        zunId: bigint;
        name: string;
        founderArbanId: bigint;
        elderSeatId: bigint;
        isActive: boolean;
        createdAt: bigint;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "INITIAL_ORG_SIZE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "KHURAL_AGE_LIMIT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_ORG_MEMBERS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "addChild"
  ): TypedContractMethod<
    [arbanId: BigNumberish, childSeatId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addOrgMember"
  ): TypedContractMethod<
    [arbanId: BigNumberish, seatId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "changeHeir"
  ): TypedContractMethod<
    [arbanId: BigNumberish, newHeirSeatId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "childCreatesOwnArban"
  ): TypedContractMethod<
    [
      parentArbanId: BigNumberish,
      childSeatId: BigNumberish,
      spouseSeatId: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createDepartment"
  ): TypedContractMethod<
    [parentOrgId: BigNumberish, deptName: string],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createOrganizationalArban"
  ): TypedContractMethod<
    [name: string, orgType: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "familyArbans"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint
      ] & {
        arbanId: bigint;
        husbandSeatId: bigint;
        wifeSeatId: bigint;
        heirSeatId: bigint;
        zunId: bigint;
        khuralRepSeatId: bigint;
        khuralRepBirthYear: bigint;
        isActive: boolean;
        createdAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "formScientificCouncil"
  ): TypedContractMethod<[name: string], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "formZun"
  ): TypedContractMethod<
    [zunName: string, arbanIds: BigNumberish[]],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getArbanTypeForSeat"
  ): TypedContractMethod<
    [seatId: BigNumberish],
    [[bigint, bigint] & { arbanType: bigint; arbanId: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getFamilyArban"
  ): TypedContractMethod<
    [arbanId: BigNumberish],
    [
      [bigint, bigint, bigint[], bigint, bigint, bigint, boolean] & {
        husbandSeatId: bigint;
        wifeSeatId: bigint;
        childrenSeatIds: bigint[];
        heirSeatId: bigint;
        zunId: bigint;
        khuralRepSeatId: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getKhuralRepresentatives"
  ): TypedContractMethod<[], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getOrgArban"
  ): TypedContractMethod<
    [arbanId: BigNumberish],
    [
      [string, bigint[], bigint, bigint, bigint, boolean] & {
        name: string;
        memberSeatIds: bigint[];
        leaderSeatId: bigint;
        orgType: bigint;
        powerBranch: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getZun"
  ): TypedContractMethod<
    [zunId: BigNumberish],
    [
      [string, bigint, bigint[], bigint, boolean] & {
        name: string;
        founderArbanId: bigint;
        memberArbanIds: bigint[];
        elderSeatId: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "isEligibleForTier2"
  ): TypedContractMethod<[seatId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "isEligibleForTier3"
  ): TypedContractMethod<[seatId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "isMarried"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "isValidKhuralRepresentative"
  ): TypedContractMethod<
    [arbanId: BigNumberish, seatId: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "nextFamilyArbanId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "nextOrgArbanId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "nextZunId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "orgArbans"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, bigint, bigint, bigint, boolean, bigint] & {
        arbanId: bigint;
        name: string;
        leaderSeatId: bigint;
        orgType: bigint;
        powerBranch: bigint;
        parentOrgId: bigint;
        isActive: boolean;
        createdAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerMarriage"
  ): TypedContractMethod<
    [husbandSeatId: BigNumberish, wifeSeatId: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "scientificCouncilId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "seatToFamilyArban"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "seatToOrgArban"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "setKhuralRepresentative"
  ): TypedContractMethod<
    [arbanId: BigNumberish, repSeatId: BigNumberish, birthYear: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setOrgLeader"
  ): TypedContractMethod<
    [arbanId: BigNumberish, leaderSeatId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setZunElder"
  ): TypedContractMethod<
    [zunId: BigNumberish, elderSeatId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "totalFamilyArbans"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalOrgArbans"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "zuns"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, bigint, boolean, bigint] & {
        zunId: bigint;
        name: string;
        founderArbanId: bigint;
        elderSeatId: bigint;
        isActive: boolean;
        createdAt: bigint;
      }
    ],
    "view"
  >;

  getEvent(
    key: "ArbanJoinedZun"
  ): TypedContractEvent<
    ArbanJoinedZunEvent.InputTuple,
    ArbanJoinedZunEvent.OutputTuple,
    ArbanJoinedZunEvent.OutputObject
  >;
  getEvent(
    key: "ChildAdded"
  ): TypedContractEvent<
    ChildAddedEvent.InputTuple,
    ChildAddedEvent.OutputTuple,
    ChildAddedEvent.OutputObject
  >;
  getEvent(
    key: "ChildCreatedOwnArban"
  ): TypedContractEvent<
    ChildCreatedOwnArbanEvent.InputTuple,
    ChildCreatedOwnArbanEvent.OutputTuple,
    ChildCreatedOwnArbanEvent.OutputObject
  >;
  getEvent(
    key: "DepartmentCreated"
  ): TypedContractEvent<
    DepartmentCreatedEvent.InputTuple,
    DepartmentCreatedEvent.OutputTuple,
    DepartmentCreatedEvent.OutputObject
  >;
  getEvent(
    key: "HeirChanged"
  ): TypedContractEvent<
    HeirChangedEvent.InputTuple,
    HeirChangedEvent.OutputTuple,
    HeirChangedEvent.OutputObject
  >;
  getEvent(
    key: "HeirSet"
  ): TypedContractEvent<
    HeirSetEvent.InputTuple,
    HeirSetEvent.OutputTuple,
    HeirSetEvent.OutputObject
  >;
  getEvent(
    key: "KhuralRepresentativeSet"
  ): TypedContractEvent<
    KhuralRepresentativeSetEvent.InputTuple,
    KhuralRepresentativeSetEvent.OutputTuple,
    KhuralRepresentativeSetEvent.OutputObject
  >;
  getEvent(
    key: "MarriageRegistered"
  ): TypedContractEvent<
    MarriageRegisteredEvent.InputTuple,
    MarriageRegisteredEvent.OutputTuple,
    MarriageRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "OrgArbanCreated"
  ): TypedContractEvent<
    OrgArbanCreatedEvent.InputTuple,
    OrgArbanCreatedEvent.OutputTuple,
    OrgArbanCreatedEvent.OutputObject
  >;
  getEvent(
    key: "OrgLeaderSet"
  ): TypedContractEvent<
    OrgLeaderSetEvent.InputTuple,
    OrgLeaderSetEvent.OutputTuple,
    OrgLeaderSetEvent.OutputObject
  >;
  getEvent(
    key: "OrgMemberAdded"
  ): TypedContractEvent<
    OrgMemberAddedEvent.InputTuple,
    OrgMemberAddedEvent.OutputTuple,
    OrgMemberAddedEvent.OutputObject
  >;
  getEvent(
    key: "OrgMemberRemoved"
  ): TypedContractEvent<
    OrgMemberRemovedEvent.InputTuple,
    OrgMemberRemovedEvent.OutputTuple,
    OrgMemberRemovedEvent.OutputObject
  >;
  getEvent(
    key: "OwnerChanged"
  ): TypedContractEvent<
    OwnerChangedEvent.InputTuple,
    OwnerChangedEvent.OutputTuple,
    OwnerChangedEvent.OutputObject
  >;
  getEvent(
    key: "ScientificCouncilFormed"
  ): TypedContractEvent<
    ScientificCouncilFormedEvent.InputTuple,
    ScientificCouncilFormedEvent.OutputTuple,
    ScientificCouncilFormedEvent.OutputObject
  >;
  getEvent(
    key: "ZunElderSet"
  ): TypedContractEvent<
    ZunElderSetEvent.InputTuple,
    ZunElderSetEvent.OutputTuple,
    ZunElderSetEvent.OutputObject
  >;
  getEvent(
    key: "ZunFormed"
  ): TypedContractEvent<
    ZunFormedEvent.InputTuple,
    ZunFormedEvent.OutputTuple,
    ZunFormedEvent.OutputObject
  >;

  filters: {
    "ArbanJoinedZun(uint256,uint256)": TypedContractEvent<
      ArbanJoinedZunEvent.InputTuple,
      ArbanJoinedZunEvent.OutputTuple,
      ArbanJoinedZunEvent.OutputObject
    >;
    ArbanJoinedZun: TypedContractEvent<
      ArbanJoinedZunEvent.InputTuple,
      ArbanJoinedZunEvent.OutputTuple,
      ArbanJoinedZunEvent.OutputObject
    >;

    "ChildAdded(uint256,uint256)": TypedContractEvent<
      ChildAddedEvent.InputTuple,
      ChildAddedEvent.OutputTuple,
      ChildAddedEvent.OutputObject
    >;
    ChildAdded: TypedContractEvent<
      ChildAddedEvent.InputTuple,
      ChildAddedEvent.OutputTuple,
      ChildAddedEvent.OutputObject
    >;

    "ChildCreatedOwnArban(uint256,uint256,uint256)": TypedContractEvent<
      ChildCreatedOwnArbanEvent.InputTuple,
      ChildCreatedOwnArbanEvent.OutputTuple,
      ChildCreatedOwnArbanEvent.OutputObject
    >;
    ChildCreatedOwnArban: TypedContractEvent<
      ChildCreatedOwnArbanEvent.InputTuple,
      ChildCreatedOwnArbanEvent.OutputTuple,
      ChildCreatedOwnArbanEvent.OutputObject
    >;

    "DepartmentCreated(uint256,uint256,string)": TypedContractEvent<
      DepartmentCreatedEvent.InputTuple,
      DepartmentCreatedEvent.OutputTuple,
      DepartmentCreatedEvent.OutputObject
    >;
    DepartmentCreated: TypedContractEvent<
      DepartmentCreatedEvent.InputTuple,
      DepartmentCreatedEvent.OutputTuple,
      DepartmentCreatedEvent.OutputObject
    >;

    "HeirChanged(uint256,uint256,uint256)": TypedContractEvent<
      HeirChangedEvent.InputTuple,
      HeirChangedEvent.OutputTuple,
      HeirChangedEvent.OutputObject
    >;
    HeirChanged: TypedContractEvent<
      HeirChangedEvent.InputTuple,
      HeirChangedEvent.OutputTuple,
      HeirChangedEvent.OutputObject
    >;

    "HeirSet(uint256,uint256)": TypedContractEvent<
      HeirSetEvent.InputTuple,
      HeirSetEvent.OutputTuple,
      HeirSetEvent.OutputObject
    >;
    HeirSet: TypedContractEvent<
      HeirSetEvent.InputTuple,
      HeirSetEvent.OutputTuple,
      HeirSetEvent.OutputObject
    >;

    "KhuralRepresentativeSet(uint256,uint256,uint64)": TypedContractEvent<
      KhuralRepresentativeSetEvent.InputTuple,
      KhuralRepresentativeSetEvent.OutputTuple,
      KhuralRepresentativeSetEvent.OutputObject
    >;
    KhuralRepresentativeSet: TypedContractEvent<
      KhuralRepresentativeSetEvent.InputTuple,
      KhuralRepresentativeSetEvent.OutputTuple,
      KhuralRepresentativeSetEvent.OutputObject
    >;

    "MarriageRegistered(uint256,uint256,uint256)": TypedContractEvent<
      MarriageRegisteredEvent.InputTuple,
      MarriageRegisteredEvent.OutputTuple,
      MarriageRegisteredEvent.OutputObject
    >;
    MarriageRegistered: TypedContractEvent<
      MarriageRegisteredEvent.InputTuple,
      MarriageRegisteredEvent.OutputTuple,
      MarriageRegisteredEvent.OutputObject
    >;

    "OrgArbanCreated(uint256,string,uint8,uint8)": TypedContractEvent<
      OrgArbanCreatedEvent.InputTuple,
      OrgArbanCreatedEvent.OutputTuple,
      OrgArbanCreatedEvent.OutputObject
    >;
    OrgArbanCreated: TypedContractEvent<
      OrgArbanCreatedEvent.InputTuple,
      OrgArbanCreatedEvent.OutputTuple,
      OrgArbanCreatedEvent.OutputObject
    >;

    "OrgLeaderSet(uint256,uint256)": TypedContractEvent<
      OrgLeaderSetEvent.InputTuple,
      OrgLeaderSetEvent.OutputTuple,
      OrgLeaderSetEvent.OutputObject
    >;
    OrgLeaderSet: TypedContractEvent<
      OrgLeaderSetEvent.InputTuple,
      OrgLeaderSetEvent.OutputTuple,
      OrgLeaderSetEvent.OutputObject
    >;

    "OrgMemberAdded(uint256,uint256)": TypedContractEvent<
      OrgMemberAddedEvent.InputTuple,
      OrgMemberAddedEvent.OutputTuple,
      OrgMemberAddedEvent.OutputObject
    >;
    OrgMemberAdded: TypedContractEvent<
      OrgMemberAddedEvent.InputTuple,
      OrgMemberAddedEvent.OutputTuple,
      OrgMemberAddedEvent.OutputObject
    >;

    "OrgMemberRemoved(uint256,uint256)": TypedContractEvent<
      OrgMemberRemovedEvent.InputTuple,
      OrgMemberRemovedEvent.OutputTuple,
      OrgMemberRemovedEvent.OutputObject
    >;
    OrgMemberRemoved: TypedContractEvent<
      OrgMemberRemovedEvent.InputTuple,
      OrgMemberRemovedEvent.OutputTuple,
      OrgMemberRemovedEvent.OutputObject
    >;

    "OwnerChanged(address,address)": TypedContractEvent<
      OwnerChangedEvent.InputTuple,
      OwnerChangedEvent.OutputTuple,
      OwnerChangedEvent.OutputObject
    >;
    OwnerChanged: TypedContractEvent<
      OwnerChangedEvent.InputTuple,
      OwnerChangedEvent.OutputTuple,
      OwnerChangedEvent.OutputObject
    >;

    "ScientificCouncilFormed(uint256)": TypedContractEvent<
      ScientificCouncilFormedEvent.InputTuple,
      ScientificCouncilFormedEvent.OutputTuple,
      ScientificCouncilFormedEvent.OutputObject
    >;
    ScientificCouncilFormed: TypedContractEvent<
      ScientificCouncilFormedEvent.InputTuple,
      ScientificCouncilFormedEvent.OutputTuple,
      ScientificCouncilFormedEvent.OutputObject
    >;

    "ZunElderSet(uint256,uint256)": TypedContractEvent<
      ZunElderSetEvent.InputTuple,
      ZunElderSetEvent.OutputTuple,
      ZunElderSetEvent.OutputObject
    >;
    ZunElderSet: TypedContractEvent<
      ZunElderSetEvent.InputTuple,
      ZunElderSetEvent.OutputTuple,
      ZunElderSetEvent.OutputObject
    >;

    "ZunFormed(uint256,string,uint256[])": TypedContractEvent<
      ZunFormedEvent.InputTuple,
      ZunFormedEvent.OutputTuple,
      ZunFormedEvent.OutputObject
    >;
    ZunFormed: TypedContractEvent<
      ZunFormedEvent.InputTuple,
      ZunFormedEvent.OutputTuple,
      ZunFormedEvent.OutputObject
    >;
  };
}
