/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ArbanCompletion } from "./ArbanCompletion";
export * as factories from "./factories";
export { ArbanCompletion__factory } from "./factories/ArbanCompletion__factory";
