export const TaxEngine_ABI = [
  {
    inputs: [
      { internalType: 'address', name: 'ledgerAddr', type: 'address' },
      { internalType: 'bytes32', name: 'confedAccountId', type: 'bytes32' },
    ],
    stateMutability: 'nonpayable',
    type: 'constructor',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'collector',
        type: 'address',
      },
      { indexed: false, internalType: 'bool', name: 'ok', type: 'bool' },
    ],
    name: 'CollectorSet',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'bytes32',
        name: 'confederationAccountId',
        type: 'bytes32',
      },
    ],
    name: 'ConfederationSet',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'ledger',
        type: 'address',
      },
    ],
    name: 'LedgerSet',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'oldOwner',
        type: 'address',
      },
      {
        indexed: true,
        internalType: 'address',
        name: 'newOwner',
        type: 'address',
      },
    ],
    name: 'OwnerChanged',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'bytes32',
        name: 'republicKey',
        type: 'bytes32',
      },
      {
        indexed: true,
        internalType: 'bytes32',
        name: 'republicAccountId',
        type: 'bytes32',
      },
    ],
    name: 'RepublicSet',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'bytes32',
        name: 'payerAccountId',
        type: 'bytes32',
      },
      {
        indexed: true,
        internalType: 'bytes32',
        name: 'republicKey',
        type: 'bytes32',
      },
      {
        indexed: true,
        internalType: 'bytes32',
        name: 'republicAccountId',
        type: 'bytes32',
      },
      {
        indexed: false,
        internalType: 'bytes32',
        name: 'confederationAccountId',
        type: 'bytes32',
      },
      { indexed: false, internalType: 'address', name: 'asset', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'amount', type: 'uint256' },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'republicTax',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'confedTax',
        type: 'uint256',
      },
      { indexed: false, internalType: 'bytes32', name: 'memo', type: 'bytes32' },
    ],
    name: 'TaxCollected',
    type: 'event',
  },
  {
    inputs: [],
    name: 'CONFED_BPS',
    outputs: [{ internalType: 'uint16', name: '', type: 'uint16' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'REPUBLIC_BPS',
    outputs: [{ internalType: 'uint16', name: '', type: 'uint16' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'TAX_BPS',
    outputs: [{ internalType: 'uint16', name: '', type: 'uint16' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'bytes32', name: 'payerAccountId', type: 'bytes32' },
      { internalType: 'bytes32', name: 'republicKey', type: 'bytes32' },
      { internalType: 'address', name: 'asset', type: 'address' },
      { internalType: 'uint256', name: 'amount', type: 'uint256' },
      { internalType: 'bytes32', name: 'memo', type: 'bytes32' },
    ],
    name: 'collectTax',
    outputs: [
      { internalType: 'uint256', name: 'republicTax', type: 'uint256' },
      { internalType: 'uint256', name: 'confedTax', type: 'uint256' },
    ],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'confederationAccountId',
    outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '', type: 'address' }],
    name: 'isCollector',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'ledger',
    outputs: [
      { internalType: 'contract IAltanBankLedgerTaxOps', name: '', type: 'address' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'owner',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'amount', type: 'uint256' }],
    name: 'quoteTax',
    outputs: [
      { internalType: 'uint256', name: 'republicTax', type: 'uint256' },
      { internalType: 'uint256', name: 'confedTax', type: 'uint256' },
    ],
    stateMutability: 'pure',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    name: 'republicAccountIdOf',
    outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'collector', type: 'address' },
      { internalType: 'bool', name: 'ok', type: 'bool' },
    ],
    name: 'setCollector',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'bytes32', name: 'confedAccountId', type: 'bytes32' }],
    name: 'setConfederationAccount',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'ledgerAddr', type: 'address' }],
    name: 'setLedger',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'bytes32', name: 'republicKey', type: 'bytes32' },
      { internalType: 'bytes32', name: 'republicAccountId', type: 'bytes32' },
    ],
    name: 'setRepublic',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'newOwner', type: 'address' }],
    name: 'transferOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
];
