---
id: 37666005-b183-4eac-a86d-8023aa7c4b0d
---
flowchart LR
P((Народ)) --> R[Регистрация / SeatSBT]
R --> C((Гражданин / SeatSBT))

%% ВОЕННЫЙ ПУТЬ (влево)
subgraph MILPATH [Военный путь]
direction RL
M1((Арбан 10))
M2((Зуун 100))
M3((Мянган 1000))
M4((Тумен 10000))
M1 --> M2
M2 --> M3
M3 --> M4
end
C --> M1

%% ЭКОНОМИЧЕСКИЙ ПУТЬ (вправо)
subgraph ECON [Экономический путь]
direction LR
L1((Арбан 10))
L2((Зуун 100))
L3((Мянган 1000))
L4((Тумен 10000))
L1 --> L2
L2 --> L3
L3 --> L4
end
C --> L1

%% РЫНОК
subgraph MARKET [РЫНОК SIMEX и экономика]
direction TB
MK[Сибирская международная биржа SIMEX]

subgraph Firms [Предприятия]
direction LR
GE[Гос. предприятия]
PE[Частные предприятия]
BK[Гос-частные банки]
ZF[Заводы и фабрики]
LG[Логистика]
LT[Рынок труда]
SV[Госуслуги и провайдеры]
end

subgraph Exchange [Биржевые рынки]
direction LR
FX[Валюта ALTN/FX]
CM[Ресурсы/товары]
EQ[Акции/доли]
DR[Производные]
CC[Карбоновые кредиты]
REA[Недвижимость]
end

MK --> GE
MK --> PE
MK --> BK
MK --> ZF
MK --> LG
MK --> LT
MK --> SV
MK --> FX
MK --> CM
MK --> EQ
MK --> DR
MK --> CC
MK --> REA
end
L4 --> MK

%% ПОЛИТИЧЕСКИЙ ПУТЬ (вправо)
subgraph GOVPATH [Политический путь]
direction LR
G1((Арбан 10))
G2((Зуун 100))
G3((Мянган 1000))
G4((Тумен 10000))
G1 --> G2
G2 --> G3
G3 --> G4
end
C --> G1

K[Хурал]
B[Центральный банк]
J[Судебная власть]
E[Исполнительная власть]
G4 --> K
G4 --> B
G4 --> J
G4 --> E

%% ЗАКОНОДАТЕЛЬНАЯ
subgraph LEGIS [Законодательная ветвь / Хурал]
direction LR
K1[Конституция и права]
K2[Бюджет и налоги]
K3[Международные дела]
K4[Природные ресурсы]
K5[Образование и здравоохранение]
K6[Данные и реестры]
K7[Счетная палата и аудит]
end
K --> K1
K --> K2
K --> K3
K --> K4
K --> K5
K --> K6
K --> K7

%% ФИНАНСОВАЯ (ЦБ)
subgraph FIN [Финансовая ветвь / ЦБ Altan]
direction LR
B1[ДКП]
B2[Платежная система / CBDC]
B3[Эмиссия и казначейство]
B4[Надзор и лицензирование]
B5[Суверенный фонд]
B6[Финстабильность]
B7[Клиринг и коррсчета]
end
B --> B1
B --> B2
B --> B3
B --> B4
B --> B5
B --> B6
B --> B7

%% СУДЕБНАЯ
subgraph JUD [Судебная ветвь]
direction LR
J1[Верховный суд]
J2[Конституционный суд]
J3[Апелляционные суды]
J4[Административные суды]
J5[Арбитражные и экономические]
J6[Антикоррупционный суд]
J7[Избирательный трибунал]
J8[Нотариат и юр. реестры]
end
J --> J1
J --> J2
J --> J3
J --> J4
J --> J5
J --> J6
J --> J7
J --> J8

%% ИСПОЛНИТЕЛЬНАЯ
subgraph EXEC [Исполнительная ветвь]
direction LR
E1[Кабинет / Премьер]
E2[Цифровое управление]
E3[Минфин]
E4[Экономика и торговля]
E5[Внутренние дела]
E6[Транспорт и логистика]
E7[Энергетика и недра]
E8[Сельское хозяйство]
E9[Здравоохранение]
E10[Образование и наука]
E11[Экология]
E12[Культура и наследие]
E13[Антикоррупция]
end
E --> E1
E --> E2
E --> E3
E --> E4
E --> E5
E --> E6
E --> E7
E --> E8
E --> E9
E --> E10
E --> E11
E --> E12
E --> E13

%% ВОЕННЫЕ ВЕТВИ
MA[Армия]
MN[Флот]
MS[Авиация и космос]
M4 --> MA
M4 --> MN
M4 --> MS

subgraph MIL_ARMY [Армия / штабы и агентства]
direction LR
MA1[Генштаб]
MA2[Сухопутные корпуса]
MA3[Тероборона]
MA4[Тыл и логистика]
MA5[Военно-медицинская]
MA6[Инженерные войска]
MA7[Кибер и связь]
MA8[Закупки и снабжение]
end
MA --> MA1
MA --> MA2
MA --> MA3
MA --> MA4
MA --> MA5
MA --> MA6
MA --> MA7
MA --> MA8

subgraph MIL_NAVY [Флот / командования и верфи]
direction LR
MN1[Командование флота]
MN2[Поверхностный флот]
MN3[Подводные силы]
MN4[Морская авиация]
MN5[Береговая охрана]
MN6[Верфи и ремонт]
MN7[Гидрография и навигация]
MN8[Логистика флота]
end
MN --> MN1
MN --> MN2
MN --> MN3
MN --> MN4
MN --> MN5
MN --> MN6
MN --> MN7
MN --> MN8

subgraph MIL_AIR [Авиация и космос / команды]
direction LR
MS1[Командование ВВС]
MS2[ПВО]
MS3[Космическое командование]
MS4[БПЛА и РЭБ]
MS5[Навигация и связь]
MS6[Техобслуживание]
MS7[Логистика и топливо]
MS8[Закупки и НИОКР]
end
MS --> MS1
MS --> MS2
MS --> MS3
MS --> MS4
MS --> MS5
MS --> MS6
MS --> MS7
MS --> MS8

%% ЮРИДИЧЕСКОЕ ЯДРО
subgraph CORE [Юридическое ядро: смарт-контракты и реестры]
direction TB
SC[Смарт-контракты Altan Chain]
RG[Единый реестр прав и актов]
CV[Акты жизни: рождение, смерть, брак, наследство]
NT[Нотариусы: доступ и заверение]
end
SC --> RG
RG --> CV
NT --> RG
NT --> SC

%% Привязки к ядру и рынку
K6 --> RG
J8 --> NT
J1 --> RG
B2 --> SC
E2 --> SC
MK --> SC
MK --> RG
MA8 --> MK
MN6 --> MK
MS8 --> MK