---
id: 2c6bf012-088c-4c83-81b7-ad496a6ec9f0
---
flowchart TD
    CB["Central Bank"] --- NB1["National Bank 1"] & NB2["National Bank 2"] & NB3["National Bank 3"] & NB4["National Bank 4"] & NB5["National Bank 5"] & NB6["National Bank 6"] & NB7["National Bank 7"] & NB8["National Bank 8"] & NB9["National Bank 9"]

    style CB stroke:#00C853
    style NB1 stroke:#00C853
    style NB2 stroke:#00C853
    style NB3 stroke:#00C853
    style NB4 stroke:#00C853
    style NB5 stroke:#00C853
    style NB6 stroke:#00C853
    style NB7 stroke:#00C853
    style NB8 stroke:#00C853
    style NB9 stroke:#00C853