---
id: 26018cdc-2467-4359-b9c2-6a03490d0883
---
flowchart TB
T[Tumen Leader]

M1[Myangan Leader 1]
M2[Myangan Leader 2]
M3[Myangan Leader 3]
M4[Myangan Leader 4]
M5[Myangan Leader 5]
M6[Myangan Leader 6]
M7[Myangan Leader 7]
M8[Myangan Leader 8]
M9[Myangan Leader 9]

T --> M1
T --> M2
T --> M3
T --> M4
T --> M5
T --> M6
T --> M7
T --> M8
T --> M9