---
id: 8dbe08a3-3e32-48e9-b0d3-bb5925452e46
---
flowchart TB
MY[Myangan Leader]

Z1[Zuun Leader 1]
Z2[Zuun Leader 2]
Z3[Zuun Leader 3]
Z4[Zuun Leader 4]
Z5[Zuun Leader 5]
Z6[Zuun Leader 6]
Z7[Zuun Leader 7]
Z8[Zuun Leader 8]
Z9[Zuun Leader 9]

MY --- Z1
MY --- Z2
MY --- Z3
MY --- Z4
MY --- Z5
MY --- Z6
MY --- Z7
MY --- Z8
MY --- Z9